const {test,expect}=require('@playwright/test')
test('real Stockfish responds; undo, reset and black-side play work without Firebase',async({page})=>{
 const errors=[]; const requests=[]
 page.on('pageerror',e=>errors.push(e.message))
 page.on('request',r=>requests.push(r.url()))
 await page.goto('/')
 expect(await page.evaluate(()=>crossOriginIsolated)).toBe(true)
 await expect(page.getByRole('heading',{name:"Let's play."})).toBeVisible()
 await page.locator('[data-squareid="e2"]').click()
 await page.locator('[data-squareid="e4"]').click()
 await expect(page.locator('.move-list')).toContainText(/^1\. e4 \S+/,{timeout:30000})
 await page.getByRole('button',{name:'Undo',exact:true}).click()
 await expect(page.locator('.move-list')).toHaveText('The opening is yours.')
 await page.getByLabel('Your pieces').selectOption('b')
 await expect(page.locator('.move-list')).toContainText(/^1\. \S+/,{timeout:30000})
 await page.getByLabel('Your pieces').selectOption('w')
 await page.getByRole('button',{name:'New game',exact:true}).click()
 await expect(page.locator('.move-list')).toHaveText('The opening is yours.')
 expect(requests.some(url=>/firebaseio|firestore.googleapis/.test(url))).toBe(false)
 expect(errors).toEqual([])
 await page.screenshot({path:'artifacts/desktop.png',fullPage:true})
})
test('mobile layout fits viewport and an invalid invitation does not break local play',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await page.goto('/?game=invalid')
 await expect(page.getByRole('heading',{name:"Let's play."})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'artifacts/mobile.png',fullPage:true})
})

test('keyboard moves, refresh recovery and pawn underpromotion work',async({page})=>{
 await page.goto('/')
 await page.getByLabel('Enter a move').fill('e4')
 await page.getByRole('button',{name:'Move',exact:true}).click()
 await expect(page.locator('.move-list')).toContainText(/^1\. e4 \S+/,{timeout:30000})
 const history=await page.locator('.move-list').textContent()
 await page.reload()
 await expect(page.locator('.move-list')).toHaveText(history)
 await page.evaluate(()=>sessionStorage.setItem('gnap-chess-local-v1','[SetUp "1"]\n[FEN "7k/P7/8/8/8/8/8/7K w - - 0 1"]\n\n*'))
 await page.reload()
 await page.locator('[data-squareid="a7"]').click()
 await page.locator('[data-squareid="a8"]').click()
 await page.getByRole('button',{name:'Knight',exact:true}).click()
 await expect(page.locator('.move-list')).toContainText('a8=N')
 await expect(page.getByRole('status')).toHaveText('Draw')
})
